# fly.toml app configuration file generated for event-processor-morning-darkness-7760 on 2025-06-25T00:15:16-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'event-processor-morning-darkness-7760'
primary_region = 'iad'

[build]

[env]
  REDIS_URL = 'redis://localhost:6379'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
